" WARNING: Do not edit this file directly. It is generated by scripts/build.js.

if exists("syntax_on")
  syntax reset
endif

set fillchars=
highlight clear
let g:colors_name = "europa"

function! s:h(group, fg, bg, style) abort
  let l:fg = empty(a:fg) ? "NONE" : a:fg
  let l:bg = empty(a:bg) ? "NONE" : a:bg
  let l:style = empty(a:style) ? "NONE" : a:style
  execute "highlight " . a:group . " guifg=" . l:fg . " guibg=" . l:bg . " gui=" . l:style . " cterm=NONE term=NONE"
endfunction

if &background ==# "light"
let g:terminal_color_0 = "#F8FBFC"
let g:terminal_color_1 = "#9E483E"
let g:terminal_color_2 = "#617A43"
let g:terminal_color_3 = "#80652F"
let g:terminal_color_4 = "#4779B1"
let g:terminal_color_5 = "#985F86"
let g:terminal_color_6 = "#4B8FA0"
let g:terminal_color_7 = "#172B35"
let g:terminal_color_8 = "#78909A"
let g:terminal_color_9 = "#A85E68"
let g:terminal_color_10 = "#4D8377"
let g:terminal_color_11 = "#726A35"
let g:terminal_color_12 = "#656CAD"
let g:terminal_color_13 = "#7B62A2"
let g:terminal_color_14 = "#4B8FA0"
let g:terminal_color_15 = "#FFFFFF"
call s:h("Normal", "#172B35", "#F8FBFC", "NONE")
call s:h("Comment", "#78909A", "NONE", "italic")
call s:h("Constant", "#4B8FA0", "NONE", "NONE")
call s:h("String", "#4D8377", "NONE", "NONE")
call s:h("Character", "#4D8377", "NONE", "NONE")
call s:h("Number", "#726A35", "NONE", "NONE")
call s:h("Boolean", "#726A35", "NONE", "NONE")
call s:h("Float", "#726A35", "NONE", "NONE")
call s:h("Identifier", "#4779B1", "NONE", "NONE")
call s:h("Function", "#4779B1", "NONE", "NONE")
call s:h("Statement", "#80652F", "NONE", "NONE")
call s:h("Conditional", "#80652F", "NONE", "NONE")
call s:h("Repeat", "#80652F", "NONE", "NONE")
call s:h("Label", "#80652F", "NONE", "NONE")
call s:h("Operator", "#656CAD", "NONE", "NONE")
call s:h("Keyword", "#80652F", "NONE", "NONE")
call s:h("Exception", "#9E483E", "NONE", "NONE")
call s:h("PreProc", "#7B62A2", "NONE", "NONE")
call s:h("Include", "#7B62A2", "NONE", "NONE")
call s:h("Define", "#7B62A2", "NONE", "NONE")
call s:h("Macro", "#7B62A2", "NONE", "NONE")
call s:h("PreCondit", "#7B62A2", "NONE", "NONE")
call s:h("Type", "#617A43", "NONE", "NONE")
call s:h("StorageClass", "#617A43", "NONE", "NONE")
call s:h("Structure", "#617A43", "NONE", "NONE")
call s:h("Typedef", "#617A43", "NONE", "NONE")
call s:h("Special", "#9F5C2D", "NONE", "NONE")
call s:h("SpecialChar", "#A85E68", "NONE", "NONE")
call s:h("Tag", "#4779B1", "NONE", "NONE")
call s:h("Delimiter", "#656CAD", "NONE", "NONE")
call s:h("SpecialComment", "#78909A", "NONE", "NONE")
call s:h("Debug", "#9E483E", "NONE", "NONE")
call s:h("Underlined", "#985F86", "NONE", "underline")
call s:h("Ignore", "#78909A", "NONE", "NONE")
call s:h("Error", "#9E483E", "NONE", "NONE")
call s:h("Todo", "#F8FBFC", "#4B8FA0", "bold")
call s:h("Cursor", "#F8FBFC", "#172B35", "NONE")
call s:h("CursorLine", "NONE", "#DCE9ED", "NONE")
call s:h("CursorLineNr", "#4B8FA0", "#DCE9ED", "bold")
call s:h("LineNr", "#78909A", "NONE", "NONE")
call s:h("SignColumn", "#78909A", "#F8FBFC", "NONE")
call s:h("ColorColumn", "NONE", "#DCE9ED", "NONE")
call s:h("VertSplit", "#C0D0D6", "#F8FBFC", "NONE")
call s:h("StatusLine", "#172B35", "#DCE9ED", "NONE")
call s:h("StatusLineNC", "#78909A", "#DCE9ED", "NONE")
call s:h("Pmenu", "#172B35", "#EEF5F7", "NONE")
call s:h("PmenuSel", "#F8FBFC", "#4B8FA0", "NONE")
call s:h("PmenuSbar", "NONE", "#DCE9ED", "NONE")
call s:h("PmenuThumb", "NONE", "#8EA5AE", "NONE")
call s:h("Visual", "NONE", "#C3DDE6", "NONE")
call s:h("VisualNOS", "NONE", "#C3DDE6", "NONE")
call s:h("Search", "#F8FBFC", "#726A35", "NONE")
call s:h("IncSearch", "#F8FBFC", "#4B8FA0", "NONE")
call s:h("MatchParen", "#4B8FA0", "#DCE9ED", "bold")
call s:h("ErrorMsg", "#9E483E", "NONE", "NONE")
call s:h("WarningMsg", "#80652F", "NONE", "NONE")
call s:h("MoreMsg", "#4B8FA0", "NONE", "NONE")
call s:h("Question", "#4B8FA0", "NONE", "NONE")
call s:h("Directory", "#4B8FA0", "NONE", "NONE")
call s:h("Folded", "#4D6571", "#DCE9ED", "NONE")
call s:h("FoldColumn", "#78909A", "#F8FBFC", "NONE")
call s:h("DiffAdd", "#F8FBFC", "#617A43", "NONE")
call s:h("DiffChange", "#F8FBFC", "#80652F", "NONE")
call s:h("DiffDelete", "#9E483E", "#F8FBFC", "NONE")
call s:h("DiffText", "#F8FBFC", "#80652F", "bold")
call s:h("SpellBad", "#9E483E", "NONE", "undercurl")
call s:h("SpellCap", "#80652F", "NONE", "undercurl")
call s:h("SpellRare", "#985F86", "NONE", "undercurl")
call s:h("SpellLocal", "#4B8FA0", "NONE", "undercurl")
call s:h("NonText", "#78909A", "NONE", "NONE")
call s:h("EndOfBuffer", "#78909A", "NONE", "NONE")
call s:h("SpecialKey", "#9F5C2D", "NONE", "NONE")
call s:h("Title", "#9F5C2D", "NONE", "bold")
else
let g:terminal_color_0 = "#0D1A24"
let g:terminal_color_1 = "#E57965"
let g:terminal_color_2 = "#B7D694"
let g:terminal_color_3 = "#D9B35F"
let g:terminal_color_4 = "#93C7F5"
let g:terminal_color_5 = "#E79BD0"
let g:terminal_color_6 = "#A6E8F4"
let g:terminal_color_7 = "#E7EEF2"
let g:terminal_color_8 = "#7F98A4"
let g:terminal_color_9 = "#F29BA4"
let g:terminal_color_10 = "#93DBC9"
let g:terminal_color_11 = "#E3D789"
let g:terminal_color_12 = "#A9ADF6"
let g:terminal_color_13 = "#C2A6F0"
let g:terminal_color_14 = "#A6E8F4"
let g:terminal_color_15 = "#F5FAFD"
call s:h("Normal", "#E7EEF2", "#0D1A24", "NONE")
call s:h("Comment", "#7F98A4", "NONE", "italic")
call s:h("Constant", "#A6E8F4", "NONE", "NONE")
call s:h("String", "#93DBC9", "NONE", "NONE")
call s:h("Character", "#93DBC9", "NONE", "NONE")
call s:h("Number", "#E3D789", "NONE", "NONE")
call s:h("Boolean", "#E3D789", "NONE", "NONE")
call s:h("Float", "#E3D789", "NONE", "NONE")
call s:h("Identifier", "#93C7F5", "NONE", "NONE")
call s:h("Function", "#93C7F5", "NONE", "NONE")
call s:h("Statement", "#D9B35F", "NONE", "NONE")
call s:h("Conditional", "#D9B35F", "NONE", "NONE")
call s:h("Repeat", "#D9B35F", "NONE", "NONE")
call s:h("Label", "#D9B35F", "NONE", "NONE")
call s:h("Operator", "#A9ADF6", "NONE", "NONE")
call s:h("Keyword", "#D9B35F", "NONE", "NONE")
call s:h("Exception", "#E57965", "NONE", "NONE")
call s:h("PreProc", "#C2A6F0", "NONE", "NONE")
call s:h("Include", "#C2A6F0", "NONE", "NONE")
call s:h("Define", "#C2A6F0", "NONE", "NONE")
call s:h("Macro", "#C2A6F0", "NONE", "NONE")
call s:h("PreCondit", "#C2A6F0", "NONE", "NONE")
call s:h("Type", "#B7D694", "NONE", "NONE")
call s:h("StorageClass", "#B7D694", "NONE", "NONE")
call s:h("Structure", "#B7D694", "NONE", "NONE")
call s:h("Typedef", "#B7D694", "NONE", "NONE")
call s:h("Special", "#E69554", "NONE", "NONE")
call s:h("SpecialChar", "#F29BA4", "NONE", "NONE")
call s:h("Tag", "#93C7F5", "NONE", "NONE")
call s:h("Delimiter", "#A9ADF6", "NONE", "NONE")
call s:h("SpecialComment", "#7F98A4", "NONE", "NONE")
call s:h("Debug", "#E57965", "NONE", "NONE")
call s:h("Underlined", "#E79BD0", "NONE", "underline")
call s:h("Ignore", "#7F98A4", "NONE", "NONE")
call s:h("Error", "#E57965", "NONE", "NONE")
call s:h("Todo", "#0D1A24", "#A6E8F4", "bold")
call s:h("Cursor", "#0D1A24", "#E7EEF2", "NONE")
call s:h("CursorLine", "NONE", "#203342", "NONE")
call s:h("CursorLineNr", "#A6E8F4", "#203342", "bold")
call s:h("LineNr", "#7F98A4", "NONE", "NONE")
call s:h("SignColumn", "#7F98A4", "#0D1A24", "NONE")
call s:h("ColorColumn", "NONE", "#203342", "NONE")
call s:h("VertSplit", "#3B5360", "#0D1A24", "NONE")
call s:h("StatusLine", "#E7EEF2", "#203342", "NONE")
call s:h("StatusLineNC", "#7F98A4", "#203342", "NONE")
call s:h("Pmenu", "#E7EEF2", "#142532", "NONE")
call s:h("PmenuSel", "#0D1A24", "#A6E8F4", "NONE")
call s:h("PmenuSbar", "NONE", "#203342", "NONE")
call s:h("PmenuThumb", "NONE", "#7893A0", "NONE")
call s:h("Visual", "NONE", "#34576B", "NONE")
call s:h("VisualNOS", "NONE", "#34576B", "NONE")
call s:h("Search", "#0D1A24", "#E3D789", "NONE")
call s:h("IncSearch", "#0D1A24", "#A6E8F4", "NONE")
call s:h("MatchParen", "#A6E8F4", "#203342", "bold")
call s:h("ErrorMsg", "#E57965", "NONE", "NONE")
call s:h("WarningMsg", "#D9B35F", "NONE", "NONE")
call s:h("MoreMsg", "#A6E8F4", "NONE", "NONE")
call s:h("Question", "#A6E8F4", "NONE", "NONE")
call s:h("Directory", "#A6E8F4", "NONE", "NONE")
call s:h("Folded", "#BAC9D0", "#203342", "NONE")
call s:h("FoldColumn", "#7F98A4", "#0D1A24", "NONE")
call s:h("DiffAdd", "#0D1A24", "#B7D694", "NONE")
call s:h("DiffChange", "#0D1A24", "#D9B35F", "NONE")
call s:h("DiffDelete", "#E57965", "#0D1A24", "NONE")
call s:h("DiffText", "#0D1A24", "#D9B35F", "bold")
call s:h("SpellBad", "#E57965", "NONE", "undercurl")
call s:h("SpellCap", "#D9B35F", "NONE", "undercurl")
call s:h("SpellRare", "#E79BD0", "NONE", "undercurl")
call s:h("SpellLocal", "#A6E8F4", "NONE", "undercurl")
call s:h("NonText", "#7F98A4", "NONE", "NONE")
call s:h("EndOfBuffer", "#7F98A4", "NONE", "NONE")
call s:h("SpecialKey", "#E69554", "NONE", "NONE")
call s:h("Title", "#E69554", "NONE", "bold")
endif
