" WARNING: Do not edit this file directly. It is generated by scripts/build.js.

let s:variant = get(g:, "jupiter_variant", "metis")

if s:variant ==# "" || s:variant ==# "jupiter"
  let s:variant = "metis"
endif

if s:variant ==# "metis"
  colorscheme metis
elseif s:variant ==# "ganymede"
  colorscheme ganymede
elseif s:variant ==# "callisto"
  colorscheme callisto
elseif s:variant ==# "europa"
  colorscheme europa
else
  echoerr "Jupiter variant must be one of: metis, ganymede, callisto, europa"
endif
