" WARNING: Do not edit this file directly. It is generated by scripts/build.js.

if exists("syntax_on")
  syntax reset
endif

set fillchars=
highlight clear
let g:colors_name = "metis"

function! s:h(group, fg, bg, style) abort
  let l:fg = empty(a:fg) ? "NONE" : a:fg
  let l:bg = empty(a:bg) ? "NONE" : a:bg
  let l:style = empty(a:style) ? "NONE" : a:style
  execute "highlight " . a:group . " guifg=" . l:fg . " guibg=" . l:bg . " gui=" . l:style . " cterm=NONE term=NONE"
endfunction

if &background ==# "light"
let g:terminal_color_0 = "#F7FCFE"
let g:terminal_color_1 = "#B73D38"
let g:terminal_color_2 = "#74772E"
let g:terminal_color_3 = "#946E00"
let g:terminal_color_4 = "#0877A8"
let g:terminal_color_5 = "#A84D5E"
let g:terminal_color_6 = "#007FA3"
let g:terminal_color_7 = "#0B2F44"
let g:terminal_color_8 = "#5C8396"
let g:terminal_color_9 = "#B85752"
let g:terminal_color_10 = "#27826F"
let g:terminal_color_11 = "#836F0A"
let g:terminal_color_12 = "#4A6FA5"
let g:terminal_color_13 = "#675FA3"
let g:terminal_color_14 = "#007FA3"
let g:terminal_color_15 = "#FFFFFF"
call s:h("Normal", "#0B2F44", "#F7FCFE", "NONE")
call s:h("Comment", "#5C8396", "NONE", "italic")
call s:h("Constant", "#007FA3", "NONE", "NONE")
call s:h("String", "#27826F", "NONE", "NONE")
call s:h("Character", "#27826F", "NONE", "NONE")
call s:h("Number", "#836F0A", "NONE", "NONE")
call s:h("Boolean", "#836F0A", "NONE", "NONE")
call s:h("Float", "#836F0A", "NONE", "NONE")
call s:h("Identifier", "#0877A8", "NONE", "NONE")
call s:h("Function", "#0877A8", "NONE", "NONE")
call s:h("Statement", "#946E00", "NONE", "NONE")
call s:h("Conditional", "#946E00", "NONE", "NONE")
call s:h("Repeat", "#946E00", "NONE", "NONE")
call s:h("Label", "#946E00", "NONE", "NONE")
call s:h("Operator", "#4A6FA5", "NONE", "NONE")
call s:h("Keyword", "#946E00", "NONE", "NONE")
call s:h("Exception", "#B73D38", "NONE", "NONE")
call s:h("PreProc", "#675FA3", "NONE", "NONE")
call s:h("Include", "#675FA3", "NONE", "NONE")
call s:h("Define", "#675FA3", "NONE", "NONE")
call s:h("Macro", "#675FA3", "NONE", "NONE")
call s:h("PreCondit", "#675FA3", "NONE", "NONE")
call s:h("Type", "#74772E", "NONE", "NONE")
call s:h("StorageClass", "#74772E", "NONE", "NONE")
call s:h("Structure", "#74772E", "NONE", "NONE")
call s:h("Typedef", "#74772E", "NONE", "NONE")
call s:h("Special", "#B75B31", "NONE", "NONE")
call s:h("SpecialChar", "#B85752", "NONE", "NONE")
call s:h("Tag", "#0877A8", "NONE", "NONE")
call s:h("Delimiter", "#4A6FA5", "NONE", "NONE")
call s:h("SpecialComment", "#5C8396", "NONE", "NONE")
call s:h("Debug", "#B73D38", "NONE", "NONE")
call s:h("Underlined", "#A84D5E", "NONE", "underline")
call s:h("Ignore", "#5C8396", "NONE", "NONE")
call s:h("Error", "#B73D38", "NONE", "NONE")
call s:h("Todo", "#F7FCFE", "#007FA3", "bold")
call s:h("Cursor", "#F7FCFE", "#0B2F44", "NONE")
call s:h("CursorLine", "NONE", "#D5EDF7", "NONE")
call s:h("CursorLineNr", "#007FA3", "#D5EDF7", "bold")
call s:h("LineNr", "#5C8396", "NONE", "NONE")
call s:h("SignColumn", "#5C8396", "#F7FCFE", "NONE")
call s:h("ColorColumn", "NONE", "#D5EDF7", "NONE")
call s:h("VertSplit", "#B9D8E6", "#F7FCFE", "NONE")
call s:h("StatusLine", "#0B2F44", "#D5EDF7", "NONE")
call s:h("StatusLineNC", "#5C8396", "#D5EDF7", "NONE")
call s:h("Pmenu", "#0B2F44", "#ECF7FC", "NONE")
call s:h("PmenuSel", "#F7FCFE", "#007FA3", "NONE")
call s:h("PmenuSbar", "NONE", "#D5EDF7", "NONE")
call s:h("PmenuThumb", "NONE", "#82B6CE", "NONE")
call s:h("Visual", "NONE", "#BAE8F6", "NONE")
call s:h("VisualNOS", "NONE", "#BAE8F6", "NONE")
call s:h("Search", "#F7FCFE", "#836F0A", "NONE")
call s:h("IncSearch", "#F7FCFE", "#007FA3", "NONE")
call s:h("MatchParen", "#007FA3", "#D5EDF7", "bold")
call s:h("ErrorMsg", "#B73D38", "NONE", "NONE")
call s:h("WarningMsg", "#946E00", "NONE", "NONE")
call s:h("MoreMsg", "#007FA3", "NONE", "NONE")
call s:h("Question", "#007FA3", "NONE", "NONE")
call s:h("Directory", "#007FA3", "NONE", "NONE")
call s:h("Folded", "#335F74", "#D5EDF7", "NONE")
call s:h("FoldColumn", "#5C8396", "#F7FCFE", "NONE")
call s:h("DiffAdd", "#F7FCFE", "#74772E", "NONE")
call s:h("DiffChange", "#F7FCFE", "#946E00", "NONE")
call s:h("DiffDelete", "#B73D38", "#F7FCFE", "NONE")
call s:h("DiffText", "#F7FCFE", "#946E00", "bold")
call s:h("SpellBad", "#B73D38", "NONE", "undercurl")
call s:h("SpellCap", "#946E00", "NONE", "undercurl")
call s:h("SpellRare", "#A84D5E", "NONE", "undercurl")
call s:h("SpellLocal", "#007FA3", "NONE", "undercurl")
call s:h("NonText", "#5C8396", "NONE", "NONE")
call s:h("EndOfBuffer", "#5C8396", "NONE", "NONE")
call s:h("SpecialKey", "#B75B31", "NONE", "NONE")
call s:h("Title", "#B75B31", "NONE", "bold")
else
let g:terminal_color_0 = "#082D42"
let g:terminal_color_1 = "#F25F57"
let g:terminal_color_2 = "#C7C46B"
let g:terminal_color_3 = "#F0A818"
let g:terminal_color_4 = "#2DA8D8"
let g:terminal_color_5 = "#DD747D"
let g:terminal_color_6 = "#38C2E6"
let g:terminal_color_7 = "#DCEBF5"
let g:terminal_color_8 = "#6096B2"
let g:terminal_color_9 = "#F07D75"
let g:terminal_color_10 = "#6BC7B5"
let g:terminal_color_11 = "#EFC852"
let g:terminal_color_12 = "#6A9BD8"
let g:terminal_color_13 = "#8C8CD7"
let g:terminal_color_14 = "#38C2E6"
let g:terminal_color_15 = "#F5FAFD"
call s:h("Normal", "#DCEBF5", "#082D42", "NONE")
call s:h("Comment", "#6096B2", "NONE", "italic")
call s:h("Constant", "#38C2E6", "NONE", "NONE")
call s:h("String", "#6BC7B5", "NONE", "NONE")
call s:h("Character", "#6BC7B5", "NONE", "NONE")
call s:h("Number", "#EFC852", "NONE", "NONE")
call s:h("Boolean", "#EFC852", "NONE", "NONE")
call s:h("Float", "#EFC852", "NONE", "NONE")
call s:h("Identifier", "#2DA8D8", "NONE", "NONE")
call s:h("Function", "#2DA8D8", "NONE", "NONE")
call s:h("Statement", "#F0A818", "NONE", "NONE")
call s:h("Conditional", "#F0A818", "NONE", "NONE")
call s:h("Repeat", "#F0A818", "NONE", "NONE")
call s:h("Label", "#F0A818", "NONE", "NONE")
call s:h("Operator", "#6A9BD8", "NONE", "NONE")
call s:h("Keyword", "#F0A818", "NONE", "NONE")
call s:h("Exception", "#F25F57", "NONE", "NONE")
call s:h("PreProc", "#8C8CD7", "NONE", "NONE")
call s:h("Include", "#8C8CD7", "NONE", "NONE")
call s:h("Define", "#8C8CD7", "NONE", "NONE")
call s:h("Macro", "#8C8CD7", "NONE", "NONE")
call s:h("PreCondit", "#8C8CD7", "NONE", "NONE")
call s:h("Type", "#C7C46B", "NONE", "NONE")
call s:h("StorageClass", "#C7C46B", "NONE", "NONE")
call s:h("Structure", "#C7C46B", "NONE", "NONE")
call s:h("Typedef", "#C7C46B", "NONE", "NONE")
call s:h("Special", "#F47B4F", "NONE", "NONE")
call s:h("SpecialChar", "#F07D75", "NONE", "NONE")
call s:h("Tag", "#2DA8D8", "NONE", "NONE")
call s:h("Delimiter", "#6A9BD8", "NONE", "NONE")
call s:h("SpecialComment", "#6096B2", "NONE", "NONE")
call s:h("Debug", "#F25F57", "NONE", "NONE")
call s:h("Underlined", "#DD747D", "NONE", "underline")
call s:h("Ignore", "#6096B2", "NONE", "NONE")
call s:h("Error", "#F25F57", "NONE", "NONE")
call s:h("Todo", "#082D42", "#38C2E6", "bold")
call s:h("Cursor", "#082D42", "#DCEBF5", "NONE")
call s:h("CursorLine", "NONE", "#104B68", "NONE")
call s:h("CursorLineNr", "#38C2E6", "#104B68", "bold")
call s:h("LineNr", "#6096B2", "NONE", "NONE")
call s:h("SignColumn", "#6096B2", "#082D42", "NONE")
call s:h("ColorColumn", "NONE", "#104B68", "NONE")
call s:h("VertSplit", "#2E6D8A", "#082D42", "NONE")
call s:h("StatusLine", "#DCEBF5", "#104B68", "NONE")
call s:h("StatusLineNC", "#6096B2", "#104B68", "NONE")
call s:h("Pmenu", "#DCEBF5", "#0B3A54", "NONE")
call s:h("PmenuSel", "#082D42", "#38C2E6", "NONE")
call s:h("PmenuSbar", "NONE", "#104B68", "NONE")
call s:h("PmenuThumb", "NONE", "#80B8D2", "NONE")
call s:h("Visual", "NONE", "#176F96", "NONE")
call s:h("VisualNOS", "NONE", "#176F96", "NONE")
call s:h("Search", "#082D42", "#EFC852", "NONE")
call s:h("IncSearch", "#082D42", "#38C2E6", "NONE")
call s:h("MatchParen", "#38C2E6", "#104B68", "bold")
call s:h("ErrorMsg", "#F25F57", "NONE", "NONE")
call s:h("WarningMsg", "#F0A818", "NONE", "NONE")
call s:h("MoreMsg", "#38C2E6", "NONE", "NONE")
call s:h("Question", "#38C2E6", "NONE", "NONE")
call s:h("Directory", "#38C2E6", "NONE", "NONE")
call s:h("Folded", "#9CCFE7", "#104B68", "NONE")
call s:h("FoldColumn", "#6096B2", "#082D42", "NONE")
call s:h("DiffAdd", "#082D42", "#C7C46B", "NONE")
call s:h("DiffChange", "#082D42", "#F0A818", "NONE")
call s:h("DiffDelete", "#F25F57", "#082D42", "NONE")
call s:h("DiffText", "#082D42", "#F0A818", "bold")
call s:h("SpellBad", "#F25F57", "NONE", "undercurl")
call s:h("SpellCap", "#F0A818", "NONE", "undercurl")
call s:h("SpellRare", "#DD747D", "NONE", "undercurl")
call s:h("SpellLocal", "#38C2E6", "NONE", "undercurl")
call s:h("NonText", "#6096B2", "NONE", "NONE")
call s:h("EndOfBuffer", "#6096B2", "NONE", "NONE")
call s:h("SpecialKey", "#F47B4F", "NONE", "NONE")
call s:h("Title", "#F47B4F", "NONE", "bold")
endif
