" WARNING: Do not edit this file directly. It is generated by scripts/build.js.

if exists("syntax_on")
  syntax reset
endif

set fillchars=
highlight clear
let g:colors_name = "metis"

function! s:h(group, fg, bg, style) abort
  let l:fg = empty(a:fg) ? "NONE" : a:fg
  let l:bg = empty(a:bg) ? "NONE" : a:bg
  let l:style = empty(a:style) ? "NONE" : a:style
  execute "highlight " . a:group . " guifg=" . l:fg . " guibg=" . l:bg . " gui=" . l:style . " cterm=NONE term=NONE"
endfunction

if &background ==# "light"
let g:terminal_color_0 = "#F7FAFC"
let g:terminal_color_1 = "#AE3431"
let g:terminal_color_2 = "#397735"
let g:terminal_color_3 = "#8F6800"
let g:terminal_color_4 = "#1A63C9"
let g:terminal_color_5 = "#A83B80"
let g:terminal_color_6 = "#007E9F"
let g:terminal_color_7 = "#172631"
let g:terminal_color_8 = "#718493"
let g:terminal_color_9 = "#BF385B"
let g:terminal_color_10 = "#1C7E67"
let g:terminal_color_11 = "#776700"
let g:terminal_color_12 = "#515ABD"
let g:terminal_color_13 = "#7446B0"
let g:terminal_color_14 = "#007E9F"
let g:terminal_color_15 = "#FFFFFF"
call s:h("Normal", "#172631", "#F7FAFC", "NONE")
call s:h("Comment", "#718493", "NONE", "italic")
call s:h("Constant", "#007E9F", "NONE", "NONE")
call s:h("String", "#1C7E67", "NONE", "NONE")
call s:h("Character", "#1C7E67", "NONE", "NONE")
call s:h("Number", "#776700", "NONE", "NONE")
call s:h("Boolean", "#776700", "NONE", "NONE")
call s:h("Float", "#776700", "NONE", "NONE")
call s:h("Identifier", "#1A63C9", "NONE", "NONE")
call s:h("Function", "#1A63C9", "NONE", "NONE")
call s:h("Statement", "#8F6800", "NONE", "NONE")
call s:h("Conditional", "#8F6800", "NONE", "NONE")
call s:h("Repeat", "#8F6800", "NONE", "NONE")
call s:h("Label", "#8F6800", "NONE", "NONE")
call s:h("Operator", "#515ABD", "NONE", "NONE")
call s:h("Keyword", "#8F6800", "NONE", "NONE")
call s:h("Exception", "#AE3431", "NONE", "NONE")
call s:h("PreProc", "#7446B0", "NONE", "NONE")
call s:h("Include", "#7446B0", "NONE", "NONE")
call s:h("Define", "#7446B0", "NONE", "NONE")
call s:h("Macro", "#7446B0", "NONE", "NONE")
call s:h("PreCondit", "#7446B0", "NONE", "NONE")
call s:h("Type", "#397735", "NONE", "NONE")
call s:h("StorageClass", "#397735", "NONE", "NONE")
call s:h("Structure", "#397735", "NONE", "NONE")
call s:h("Typedef", "#397735", "NONE", "NONE")
call s:h("Special", "#A84F22", "NONE", "NONE")
call s:h("SpecialChar", "#BF385B", "NONE", "NONE")
call s:h("Tag", "#1A63C9", "NONE", "NONE")
call s:h("Delimiter", "#515ABD", "NONE", "NONE")
call s:h("SpecialComment", "#718493", "NONE", "NONE")
call s:h("Debug", "#AE3431", "NONE", "NONE")
call s:h("Underlined", "#A83B80", "NONE", "underline")
call s:h("Ignore", "#718493", "NONE", "NONE")
call s:h("Error", "#AE3431", "NONE", "NONE")
call s:h("Todo", "#F7FAFC", "#007E9F", "bold")
call s:h("Cursor", "#F7FAFC", "#172631", "NONE")
call s:h("CursorLine", "NONE", "#DCE7EE", "NONE")
call s:h("CursorLineNr", "#007E9F", "#DCE7EE", "bold")
call s:h("LineNr", "#718493", "NONE", "NONE")
call s:h("SignColumn", "#718493", "#F7FAFC", "NONE")
call s:h("ColorColumn", "NONE", "#DCE7EE", "NONE")
call s:h("VertSplit", "#C5D4DE", "#F7FAFC", "NONE")
call s:h("StatusLine", "#172631", "#DCE7EE", "NONE")
call s:h("StatusLineNC", "#718493", "#DCE7EE", "NONE")
call s:h("Pmenu", "#172631", "#EDF4F8", "NONE")
call s:h("PmenuSel", "#F7FAFC", "#007E9F", "NONE")
call s:h("PmenuSbar", "NONE", "#DCE7EE", "NONE")
call s:h("PmenuThumb", "NONE", "#9BACB9", "NONE")
call s:h("Visual", "NONE", "#B8DAE6", "NONE")
call s:h("VisualNOS", "NONE", "#B8DAE6", "NONE")
call s:h("Search", "#F7FAFC", "#776700", "NONE")
call s:h("IncSearch", "#F7FAFC", "#007E9F", "NONE")
call s:h("MatchParen", "#007E9F", "#DCE7EE", "bold")
call s:h("ErrorMsg", "#AE3431", "NONE", "NONE")
call s:h("WarningMsg", "#8F6800", "NONE", "NONE")
call s:h("MoreMsg", "#007E9F", "NONE", "NONE")
call s:h("Question", "#007E9F", "NONE", "NONE")
call s:h("Directory", "#007E9F", "NONE", "NONE")
call s:h("Folded", "#4B6070", "#DCE7EE", "NONE")
call s:h("FoldColumn", "#718493", "#F7FAFC", "NONE")
call s:h("DiffAdd", "#F7FAFC", "#397735", "NONE")
call s:h("DiffChange", "#F7FAFC", "#8F6800", "NONE")
call s:h("DiffDelete", "#AE3431", "#F7FAFC", "NONE")
call s:h("DiffText", "#F7FAFC", "#8F6800", "bold")
call s:h("SpellBad", "#AE3431", "NONE", "undercurl")
call s:h("SpellCap", "#8F6800", "NONE", "undercurl")
call s:h("SpellRare", "#A83B80", "NONE", "undercurl")
call s:h("SpellLocal", "#007E9F", "NONE", "undercurl")
call s:h("NonText", "#718493", "NONE", "NONE")
call s:h("EndOfBuffer", "#718493", "NONE", "NONE")
call s:h("SpecialKey", "#A84F22", "NONE", "NONE")
call s:h("Title", "#A84F22", "NONE", "bold")
else
let g:terminal_color_0 = "#0C1218"
let g:terminal_color_1 = "#FF665D"
let g:terminal_color_2 = "#7FC86B"
let g:terminal_color_3 = "#F0AD2E"
let g:terminal_color_4 = "#70A8FF"
let g:terminal_color_5 = "#EB70BE"
let g:terminal_color_6 = "#4ACDEB"
let g:terminal_color_7 = "#E1EBF2"
let g:terminal_color_8 = "#7A8B98"
let g:terminal_color_9 = "#FF7795"
let g:terminal_color_10 = "#58D0A8"
let g:terminal_color_11 = "#E7C951"
let g:terminal_color_12 = "#9B9FFF"
let g:terminal_color_13 = "#B987FF"
let g:terminal_color_14 = "#4ACDEB"
let g:terminal_color_15 = "#F5FAFD"
call s:h("Normal", "#E1EBF2", "#0C1218", "NONE")
call s:h("Comment", "#7A8B98", "NONE", "italic")
call s:h("Constant", "#4ACDEB", "NONE", "NONE")
call s:h("String", "#58D0A8", "NONE", "NONE")
call s:h("Character", "#58D0A8", "NONE", "NONE")
call s:h("Number", "#E7C951", "NONE", "NONE")
call s:h("Boolean", "#E7C951", "NONE", "NONE")
call s:h("Float", "#E7C951", "NONE", "NONE")
call s:h("Identifier", "#70A8FF", "NONE", "NONE")
call s:h("Function", "#70A8FF", "NONE", "NONE")
call s:h("Statement", "#F0AD2E", "NONE", "NONE")
call s:h("Conditional", "#F0AD2E", "NONE", "NONE")
call s:h("Repeat", "#F0AD2E", "NONE", "NONE")
call s:h("Label", "#F0AD2E", "NONE", "NONE")
call s:h("Operator", "#9B9FFF", "NONE", "NONE")
call s:h("Keyword", "#F0AD2E", "NONE", "NONE")
call s:h("Exception", "#FF665D", "NONE", "NONE")
call s:h("PreProc", "#B987FF", "NONE", "NONE")
call s:h("Include", "#B987FF", "NONE", "NONE")
call s:h("Define", "#B987FF", "NONE", "NONE")
call s:h("Macro", "#B987FF", "NONE", "NONE")
call s:h("PreCondit", "#B987FF", "NONE", "NONE")
call s:h("Type", "#7FC86B", "NONE", "NONE")
call s:h("StorageClass", "#7FC86B", "NONE", "NONE")
call s:h("Structure", "#7FC86B", "NONE", "NONE")
call s:h("Typedef", "#7FC86B", "NONE", "NONE")
call s:h("Special", "#FF8B4C", "NONE", "NONE")
call s:h("SpecialChar", "#FF7795", "NONE", "NONE")
call s:h("Tag", "#70A8FF", "NONE", "NONE")
call s:h("Delimiter", "#9B9FFF", "NONE", "NONE")
call s:h("SpecialComment", "#7A8B98", "NONE", "NONE")
call s:h("Debug", "#FF665D", "NONE", "NONE")
call s:h("Underlined", "#EB70BE", "NONE", "underline")
call s:h("Ignore", "#7A8B98", "NONE", "NONE")
call s:h("Error", "#FF665D", "NONE", "NONE")
call s:h("Todo", "#0C1218", "#4ACDEB", "bold")
call s:h("Cursor", "#0C1218", "#E1EBF2", "NONE")
call s:h("CursorLine", "NONE", "#1B2834", "NONE")
call s:h("CursorLineNr", "#4ACDEB", "#1B2834", "bold")
call s:h("LineNr", "#7A8B98", "NONE", "NONE")
call s:h("SignColumn", "#7A8B98", "#0C1218", "NONE")
call s:h("ColorColumn", "NONE", "#1B2834", "NONE")
call s:h("VertSplit", "#30424F", "#0C1218", "NONE")
call s:h("StatusLine", "#E1EBF2", "#1B2834", "NONE")
call s:h("StatusLineNC", "#7A8B98", "#1B2834", "NONE")
call s:h("Pmenu", "#E1EBF2", "#131D26", "NONE")
call s:h("PmenuSel", "#0C1218", "#4ACDEB", "NONE")
call s:h("PmenuSbar", "NONE", "#1B2834", "NONE")
call s:h("PmenuThumb", "NONE", "#4A5D6E", "NONE")
call s:h("Visual", "NONE", "#24596F", "NONE")
call s:h("VisualNOS", "NONE", "#24596F", "NONE")
call s:h("Search", "#0C1218", "#E7C951", "NONE")
call s:h("IncSearch", "#0C1218", "#4ACDEB", "NONE")
call s:h("MatchParen", "#4ACDEB", "#1B2834", "bold")
call s:h("ErrorMsg", "#FF665D", "NONE", "NONE")
call s:h("WarningMsg", "#F0AD2E", "NONE", "NONE")
call s:h("MoreMsg", "#4ACDEB", "NONE", "NONE")
call s:h("Question", "#4ACDEB", "NONE", "NONE")
call s:h("Directory", "#4ACDEB", "NONE", "NONE")
call s:h("Folded", "#AFBBC4", "#1B2834", "NONE")
call s:h("FoldColumn", "#7A8B98", "#0C1218", "NONE")
call s:h("DiffAdd", "#0C1218", "#7FC86B", "NONE")
call s:h("DiffChange", "#0C1218", "#F0AD2E", "NONE")
call s:h("DiffDelete", "#FF665D", "#0C1218", "NONE")
call s:h("DiffText", "#0C1218", "#F0AD2E", "bold")
call s:h("SpellBad", "#FF665D", "NONE", "undercurl")
call s:h("SpellCap", "#F0AD2E", "NONE", "undercurl")
call s:h("SpellRare", "#EB70BE", "NONE", "undercurl")
call s:h("SpellLocal", "#4ACDEB", "NONE", "undercurl")
call s:h("NonText", "#7A8B98", "NONE", "NONE")
call s:h("EndOfBuffer", "#7A8B98", "NONE", "NONE")
call s:h("SpecialKey", "#FF8B4C", "NONE", "NONE")
call s:h("Title", "#FF8B4C", "NONE", "bold")
endif
