" WARNING: Do not edit this file directly. It is generated by scripts/build.js.

if exists("syntax_on")
  syntax reset
endif

set fillchars=
highlight clear
let g:colors_name = "metis"

function! s:h(group, fg, bg, style) abort
  let l:fg = empty(a:fg) ? "NONE" : a:fg
  let l:bg = empty(a:bg) ? "NONE" : a:bg
  let l:style = empty(a:style) ? "NONE" : a:style
  execute "highlight " . a:group . " guifg=" . l:fg . " guibg=" . l:bg . " gui=" . l:style . " cterm=NONE term=NONE"
endfunction

if &background ==# "light"
let g:terminal_color_0 = "#F8FBFD"
let g:terminal_color_1 = "#B93532"
let g:terminal_color_2 = "#3F7F38"
let g:terminal_color_3 = "#9D7100"
let g:terminal_color_4 = "#1B67D7"
let g:terminal_color_5 = "#AD3E86"
let g:terminal_color_6 = "#007FA8"
let g:terminal_color_7 = "#172530"
let g:terminal_color_8 = "#708390"
let g:terminal_color_9 = "#C83C62"
let g:terminal_color_10 = "#1F876D"
let g:terminal_color_11 = "#846F00"
let g:terminal_color_12 = "#555FCE"
let g:terminal_color_13 = "#7A4BC2"
let g:terminal_color_14 = "#007FA8"
let g:terminal_color_15 = "#FFFFFF"
call s:h("Normal", "#172530", "#F8FBFD", "NONE")
call s:h("Comment", "#708390", "NONE", "italic")
call s:h("Constant", "#007FA8", "NONE", "NONE")
call s:h("String", "#1F876D", "NONE", "NONE")
call s:h("Character", "#1F876D", "NONE", "NONE")
call s:h("Number", "#846F00", "NONE", "NONE")
call s:h("Boolean", "#846F00", "NONE", "NONE")
call s:h("Float", "#846F00", "NONE", "NONE")
call s:h("Identifier", "#1B67D7", "NONE", "NONE")
call s:h("Function", "#1B67D7", "NONE", "NONE")
call s:h("Statement", "#9D7100", "NONE", "NONE")
call s:h("Conditional", "#9D7100", "NONE", "NONE")
call s:h("Repeat", "#9D7100", "NONE", "NONE")
call s:h("Label", "#9D7100", "NONE", "NONE")
call s:h("Operator", "#555FCE", "NONE", "NONE")
call s:h("Keyword", "#9D7100", "NONE", "NONE")
call s:h("Exception", "#B93532", "NONE", "NONE")
call s:h("PreProc", "#7A4BC2", "NONE", "NONE")
call s:h("Include", "#7A4BC2", "NONE", "NONE")
call s:h("Define", "#7A4BC2", "NONE", "NONE")
call s:h("Macro", "#7A4BC2", "NONE", "NONE")
call s:h("PreCondit", "#7A4BC2", "NONE", "NONE")
call s:h("Type", "#3F7F38", "NONE", "NONE")
call s:h("StorageClass", "#3F7F38", "NONE", "NONE")
call s:h("Structure", "#3F7F38", "NONE", "NONE")
call s:h("Typedef", "#3F7F38", "NONE", "NONE")
call s:h("Special", "#B85727", "NONE", "NONE")
call s:h("SpecialChar", "#C83C62", "NONE", "NONE")
call s:h("Tag", "#1B67D7", "NONE", "NONE")
call s:h("Delimiter", "#555FCE", "NONE", "NONE")
call s:h("SpecialComment", "#708390", "NONE", "NONE")
call s:h("Debug", "#B93532", "NONE", "NONE")
call s:h("Underlined", "#AD3E86", "NONE", "underline")
call s:h("Ignore", "#708390", "NONE", "NONE")
call s:h("Error", "#B93532", "NONE", "NONE")
call s:h("Todo", "#F8FBFD", "#007FA8", "bold")
call s:h("Cursor", "#F8FBFD", "#172530", "NONE")
call s:h("CursorLine", "NONE", "#DDE8EF", "NONE")
call s:h("CursorLineNr", "#007FA8", "#DDE8EF", "bold")
call s:h("LineNr", "#708390", "NONE", "NONE")
call s:h("SignColumn", "#708390", "#F8FBFD", "NONE")
call s:h("ColorColumn", "NONE", "#DDE8EF", "NONE")
call s:h("VertSplit", "#C7D5DE", "#F8FBFD", "NONE")
call s:h("StatusLine", "#172530", "#DDE8EF", "NONE")
call s:h("StatusLineNC", "#708390", "#DDE8EF", "NONE")
call s:h("Pmenu", "#172530", "#EEF5F8", "NONE")
call s:h("PmenuSel", "#F8FBFD", "#007FA8", "NONE")
call s:h("PmenuSbar", "NONE", "#DDE8EF", "NONE")
call s:h("PmenuThumb", "NONE", "#9DAFBB", "NONE")
call s:h("Visual", "NONE", "#B9DCE8", "NONE")
call s:h("VisualNOS", "NONE", "#B9DCE8", "NONE")
call s:h("Search", "#F8FBFD", "#846F00", "NONE")
call s:h("IncSearch", "#F8FBFD", "#007FA8", "NONE")
call s:h("MatchParen", "#007FA8", "#DDE8EF", "bold")
call s:h("ErrorMsg", "#B93532", "NONE", "NONE")
call s:h("WarningMsg", "#9D7100", "NONE", "NONE")
call s:h("MoreMsg", "#007FA8", "NONE", "NONE")
call s:h("Question", "#007FA8", "NONE", "NONE")
call s:h("Directory", "#007FA8", "NONE", "NONE")
call s:h("Folded", "#4A5E6B", "#DDE8EF", "NONE")
call s:h("FoldColumn", "#708390", "#F8FBFD", "NONE")
call s:h("DiffAdd", "#F8FBFD", "#3F7F38", "NONE")
call s:h("DiffChange", "#F8FBFD", "#9D7100", "NONE")
call s:h("DiffDelete", "#B93532", "#F8FBFD", "NONE")
call s:h("DiffText", "#F8FBFD", "#9D7100", "bold")
call s:h("SpellBad", "#B93532", "NONE", "undercurl")
call s:h("SpellCap", "#9D7100", "NONE", "undercurl")
call s:h("SpellRare", "#AD3E86", "NONE", "undercurl")
call s:h("SpellLocal", "#007FA8", "NONE", "undercurl")
call s:h("NonText", "#708390", "NONE", "NONE")
call s:h("EndOfBuffer", "#708390", "NONE", "NONE")
call s:h("SpecialKey", "#B85727", "NONE", "NONE")
call s:h("Title", "#B85727", "NONE", "bold")
else
let g:terminal_color_0 = "#0B1117"
let g:terminal_color_1 = "#FF6B62"
let g:terminal_color_2 = "#82C66F"
let g:terminal_color_3 = "#F2B339"
let g:terminal_color_4 = "#69A7FF"
let g:terminal_color_5 = "#EF78C4"
let g:terminal_color_6 = "#43C7E8"
let g:terminal_color_7 = "#DCE7EF"
let g:terminal_color_8 = "#738492"
let g:terminal_color_9 = "#FF7698"
let g:terminal_color_10 = "#5DD4AF"
let g:terminal_color_11 = "#E7CF5B"
let g:terminal_color_12 = "#9AA2FF"
let g:terminal_color_13 = "#BC8FFF"
let g:terminal_color_14 = "#43C7E8"
let g:terminal_color_15 = "#F5FAFD"
call s:h("Normal", "#DCE7EF", "#0B1117", "NONE")
call s:h("Comment", "#738492", "NONE", "italic")
call s:h("Constant", "#43C7E8", "NONE", "NONE")
call s:h("String", "#5DD4AF", "NONE", "NONE")
call s:h("Character", "#5DD4AF", "NONE", "NONE")
call s:h("Number", "#E7CF5B", "NONE", "NONE")
call s:h("Boolean", "#E7CF5B", "NONE", "NONE")
call s:h("Float", "#E7CF5B", "NONE", "NONE")
call s:h("Identifier", "#69A7FF", "NONE", "NONE")
call s:h("Function", "#69A7FF", "NONE", "NONE")
call s:h("Statement", "#F2B339", "NONE", "NONE")
call s:h("Conditional", "#F2B339", "NONE", "NONE")
call s:h("Repeat", "#F2B339", "NONE", "NONE")
call s:h("Label", "#F2B339", "NONE", "NONE")
call s:h("Operator", "#9AA2FF", "NONE", "NONE")
call s:h("Keyword", "#F2B339", "NONE", "NONE")
call s:h("Exception", "#FF6B62", "NONE", "NONE")
call s:h("PreProc", "#BC8FFF", "NONE", "NONE")
call s:h("Include", "#BC8FFF", "NONE", "NONE")
call s:h("Define", "#BC8FFF", "NONE", "NONE")
call s:h("Macro", "#BC8FFF", "NONE", "NONE")
call s:h("PreCondit", "#BC8FFF", "NONE", "NONE")
call s:h("Type", "#82C66F", "NONE", "NONE")
call s:h("StorageClass", "#82C66F", "NONE", "NONE")
call s:h("Structure", "#82C66F", "NONE", "NONE")
call s:h("Typedef", "#82C66F", "NONE", "NONE")
call s:h("Special", "#FF9159", "NONE", "NONE")
call s:h("SpecialChar", "#FF7698", "NONE", "NONE")
call s:h("Tag", "#69A7FF", "NONE", "NONE")
call s:h("Delimiter", "#9AA2FF", "NONE", "NONE")
call s:h("SpecialComment", "#738492", "NONE", "NONE")
call s:h("Debug", "#FF6B62", "NONE", "NONE")
call s:h("Underlined", "#EF78C4", "NONE", "underline")
call s:h("Ignore", "#738492", "NONE", "NONE")
call s:h("Error", "#FF6B62", "NONE", "NONE")
call s:h("Todo", "#0B1117", "#43C7E8", "bold")
call s:h("Cursor", "#0B1117", "#DCE7EF", "NONE")
call s:h("CursorLine", "NONE", "#182531", "NONE")
call s:h("CursorLineNr", "#43C7E8", "#182531", "bold")
call s:h("LineNr", "#738492", "NONE", "NONE")
call s:h("SignColumn", "#738492", "#0B1117", "NONE")
call s:h("ColorColumn", "NONE", "#182531", "NONE")
call s:h("VertSplit", "#2A3A47", "#0B1117", "NONE")
call s:h("StatusLine", "#DCE7EF", "#182531", "NONE")
call s:h("StatusLineNC", "#738492", "#182531", "NONE")
call s:h("Pmenu", "#DCE7EF", "#111A23", "NONE")
call s:h("PmenuSel", "#0B1117", "#43C7E8", "NONE")
call s:h("PmenuSbar", "NONE", "#182531", "NONE")
call s:h("PmenuThumb", "NONE", "#415466", "NONE")
call s:h("Visual", "NONE", "#1F5367", "NONE")
call s:h("VisualNOS", "NONE", "#1F5367", "NONE")
call s:h("Search", "#0B1117", "#E7CF5B", "NONE")
call s:h("IncSearch", "#0B1117", "#43C7E8", "NONE")
call s:h("MatchParen", "#43C7E8", "#182531", "bold")
call s:h("ErrorMsg", "#FF6B62", "NONE", "NONE")
call s:h("WarningMsg", "#F2B339", "NONE", "NONE")
call s:h("MoreMsg", "#43C7E8", "NONE", "NONE")
call s:h("Question", "#43C7E8", "NONE", "NONE")
call s:h("Directory", "#43C7E8", "NONE", "NONE")
call s:h("Folded", "#AAB8C3", "#182531", "NONE")
call s:h("FoldColumn", "#738492", "#0B1117", "NONE")
call s:h("DiffAdd", "#0B1117", "#82C66F", "NONE")
call s:h("DiffChange", "#0B1117", "#F2B339", "NONE")
call s:h("DiffDelete", "#FF6B62", "#0B1117", "NONE")
call s:h("DiffText", "#0B1117", "#F2B339", "bold")
call s:h("SpellBad", "#FF6B62", "NONE", "undercurl")
call s:h("SpellCap", "#F2B339", "NONE", "undercurl")
call s:h("SpellRare", "#EF78C4", "NONE", "undercurl")
call s:h("SpellLocal", "#43C7E8", "NONE", "undercurl")
call s:h("NonText", "#738492", "NONE", "NONE")
call s:h("EndOfBuffer", "#738492", "NONE", "NONE")
call s:h("SpecialKey", "#FF9159", "NONE", "NONE")
call s:h("Title", "#FF9159", "NONE", "bold")
endif
