" WARNING: Do not edit this file directly. It is generated by scripts/build.js.

let g:airline#themes#callisto#palette = {}

if &background ==# "light"
let s:modified = {
  \ 'airline_c': [ "#B9353F" , "" , "" , "" , "" ]
  \ }

let s:N1 = [ "#F2F6FB" , "#007EA0" , "" , "" ]
let s:N2 = [ "#111B2A" , "#D7E1ED" , "" , "" ]
let s:N3 = [ "#40516A" , "#E8EEF7" , "" , "" ]
let g:airline#themes#callisto#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
let g:airline#themes#callisto#palette.normal_modified = s:modified

let s:I1 = [ "#F2F6FB" , "#4F7D25" , "" , "" ]
let g:airline#themes#callisto#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
let g:airline#themes#callisto#palette.insert_modified = s:modified

let s:V1 = [ "#F2F6FB" , "#A93494" , "" , "" ]
let g:airline#themes#callisto#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
let g:airline#themes#callisto#palette.visual_modified = s:modified

let s:R1 = [ "#F2F6FB" , "#B9353F" , "" , "" ]
let g:airline#themes#callisto#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
let g:airline#themes#callisto#palette.replace_modified = s:modified

let s:IN1 = [ "#66748A" , "#D7E1ED" , "" , "" ]
let g:airline#themes#callisto#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
let g:airline#themes#callisto#palette.inactive_modified = s:modified

let s:AirlineError = [ "#F2F6FB" , "#B9353F" , "" , "" ]
let s:AirlineWarning = [ "#F2F6FB" , "#8F6100" , "" , "" ]
let g:airline#themes#callisto#palette.accents = {'red': [ "#B9353F" , "" , "" , "" ]}

for s:mode in ['normal', 'insert', 'visual', 'replace']
  let g:airline#themes#callisto#palette[s:mode].airline_error = s:AirlineError
  let g:airline#themes#callisto#palette[s:mode].airline_warning = s:AirlineWarning
endfor

let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
let g:airline#themes#callisto#palette.tabline = {
  \ 'airline_tab': s:N2,
  \ 'airline_tabsel': s:N1,
  \ 'airline_tabtype': [ "#F2F6FB" , "#4F7D25" , "" , "" ],
  \ 'airline_tabfill': s:tabfill,
  \ 'airline_tabhid': s:IN1
  \ }
else
let s:modified = {
  \ 'airline_c': [ "#FF5662" , "" , "" , "" , "" ]
  \ }

let s:N1 = [ "#070B12" , "#1BD7FF" , "" , "" ]
let s:N2 = [ "#E8EEF8" , "#151E2D" , "" , "" ]
let s:N3 = [ "#B0BED3" , "#0D1320" , "" , "" ]
let g:airline#themes#callisto#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
let g:airline#themes#callisto#palette.normal_modified = s:modified

let s:I1 = [ "#070B12" , "#8CDD57" , "" , "" ]
let g:airline#themes#callisto#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
let g:airline#themes#callisto#palette.insert_modified = s:modified

let s:V1 = [ "#070B12" , "#F05ADB" , "" , "" ]
let g:airline#themes#callisto#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
let g:airline#themes#callisto#palette.visual_modified = s:modified

let s:R1 = [ "#070B12" , "#FF5662" , "" , "" ]
let g:airline#themes#callisto#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
let g:airline#themes#callisto#palette.replace_modified = s:modified

let s:IN1 = [ "#667890" , "#151E2D" , "" , "" ]
let g:airline#themes#callisto#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
let g:airline#themes#callisto#palette.inactive_modified = s:modified

let s:AirlineError = [ "#070B12" , "#FF5662" , "" , "" ]
let s:AirlineWarning = [ "#070B12" , "#FFAD13" , "" , "" ]
let g:airline#themes#callisto#palette.accents = {'red': [ "#FF5662" , "" , "" , "" ]}

for s:mode in ['normal', 'insert', 'visual', 'replace']
  let g:airline#themes#callisto#palette[s:mode].airline_error = s:AirlineError
  let g:airline#themes#callisto#palette[s:mode].airline_warning = s:AirlineWarning
endfor

let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
let g:airline#themes#callisto#palette.tabline = {
  \ 'airline_tab': s:N2,
  \ 'airline_tabsel': s:N1,
  \ 'airline_tabtype': [ "#070B12" , "#8CDD57" , "" , "" ],
  \ 'airline_tabfill': s:tabfill,
  \ 'airline_tabhid': s:IN1
  \ }
endif
