" WARNING: Do not edit this file directly. It is generated by scripts/build.js.

let g:airline#themes#europa#palette = {}

if &background ==# "light"
let s:modified = {
  \ 'airline_c': [ "#9E483E" , "" , "" , "" , "" ]
  \ }

let s:N1 = [ "#F8FBFC" , "#4B8FA0" , "" , "" ]
let s:N2 = [ "#172B35" , "#DCE9ED" , "" , "" ]
let s:N3 = [ "#4D6571" , "#EEF5F7" , "" , "" ]
let g:airline#themes#europa#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
let g:airline#themes#europa#palette.normal_modified = s:modified

let s:I1 = [ "#F8FBFC" , "#617A43" , "" , "" ]
let g:airline#themes#europa#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
let g:airline#themes#europa#palette.insert_modified = s:modified

let s:V1 = [ "#F8FBFC" , "#985F86" , "" , "" ]
let g:airline#themes#europa#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
let g:airline#themes#europa#palette.visual_modified = s:modified

let s:R1 = [ "#F8FBFC" , "#9E483E" , "" , "" ]
let g:airline#themes#europa#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
let g:airline#themes#europa#palette.replace_modified = s:modified

let s:IN1 = [ "#78909A" , "#DCE9ED" , "" , "" ]
let g:airline#themes#europa#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
let g:airline#themes#europa#palette.inactive_modified = s:modified

let s:AirlineError = [ "#F8FBFC" , "#9E483E" , "" , "" ]
let s:AirlineWarning = [ "#F8FBFC" , "#80652F" , "" , "" ]
let g:airline#themes#europa#palette.accents = {'red': [ "#9E483E" , "" , "" , "" ]}

for s:mode in ['normal', 'insert', 'visual', 'replace']
  let g:airline#themes#europa#palette[s:mode].airline_error = s:AirlineError
  let g:airline#themes#europa#palette[s:mode].airline_warning = s:AirlineWarning
endfor

let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
let g:airline#themes#europa#palette.tabline = {
  \ 'airline_tab': s:N2,
  \ 'airline_tabsel': s:N1,
  \ 'airline_tabtype': [ "#F8FBFC" , "#617A43" , "" , "" ],
  \ 'airline_tabfill': s:tabfill,
  \ 'airline_tabhid': s:IN1
  \ }
else
let s:modified = {
  \ 'airline_c': [ "#E57965" , "" , "" , "" , "" ]
  \ }

let s:N1 = [ "#0D1A24" , "#A6E8F4" , "" , "" ]
let s:N2 = [ "#E7EEF2" , "#203342" , "" , "" ]
let s:N3 = [ "#BAC9D0" , "#142532" , "" , "" ]
let g:airline#themes#europa#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
let g:airline#themes#europa#palette.normal_modified = s:modified

let s:I1 = [ "#0D1A24" , "#B7D694" , "" , "" ]
let g:airline#themes#europa#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
let g:airline#themes#europa#palette.insert_modified = s:modified

let s:V1 = [ "#0D1A24" , "#E79BD0" , "" , "" ]
let g:airline#themes#europa#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
let g:airline#themes#europa#palette.visual_modified = s:modified

let s:R1 = [ "#0D1A24" , "#E57965" , "" , "" ]
let g:airline#themes#europa#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
let g:airline#themes#europa#palette.replace_modified = s:modified

let s:IN1 = [ "#7F98A4" , "#203342" , "" , "" ]
let g:airline#themes#europa#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
let g:airline#themes#europa#palette.inactive_modified = s:modified

let s:AirlineError = [ "#0D1A24" , "#E57965" , "" , "" ]
let s:AirlineWarning = [ "#0D1A24" , "#D9B35F" , "" , "" ]
let g:airline#themes#europa#palette.accents = {'red': [ "#E57965" , "" , "" , "" ]}

for s:mode in ['normal', 'insert', 'visual', 'replace']
  let g:airline#themes#europa#palette[s:mode].airline_error = s:AirlineError
  let g:airline#themes#europa#palette[s:mode].airline_warning = s:AirlineWarning
endfor

let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
let g:airline#themes#europa#palette.tabline = {
  \ 'airline_tab': s:N2,
  \ 'airline_tabsel': s:N1,
  \ 'airline_tabtype': [ "#0D1A24" , "#B7D694" , "" , "" ],
  \ 'airline_tabfill': s:tabfill,
  \ 'airline_tabhid': s:IN1
  \ }
endif
