" WARNING: Do not edit this file directly. It is generated by scripts/build.js.

let g:airline#themes#ganymede#palette = {}

if &background ==# "light"
let s:modified = {
  \ 'airline_c': [ "#B53331" , "" , "" , "" , "" ]
  \ }

let s:N1 = [ "#F4FBFE" , "#007EA3" , "" , "" ]
let s:N2 = [ "#093750" , "#CFEAF6" , "" , "" ]
let s:N3 = [ "#315B71" , "#E7F5FB" , "" , "" ]
let g:airline#themes#ganymede#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
let g:airline#themes#ganymede#palette.normal_modified = s:modified

let s:I1 = [ "#F4FBFE" , "#6F641B" , "" , "" ]
let g:airline#themes#ganymede#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
let g:airline#themes#ganymede#palette.insert_modified = s:modified

let s:V1 = [ "#F4FBFE" , "#B6524F" , "" , "" ]
let g:airline#themes#ganymede#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
let g:airline#themes#ganymede#palette.visual_modified = s:modified

let s:R1 = [ "#F4FBFE" , "#B53331" , "" , "" ]
let g:airline#themes#ganymede#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
let g:airline#themes#ganymede#palette.replace_modified = s:modified

let s:IN1 = [ "#557E92" , "#CFEAF6" , "" , "" ]
let g:airline#themes#ganymede#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
let g:airline#themes#ganymede#palette.inactive_modified = s:modified

let s:AirlineError = [ "#F4FBFE" , "#B53331" , "" , "" ]
let s:AirlineWarning = [ "#F4FBFE" , "#B53331" , "" , "" ]
let g:airline#themes#ganymede#palette.accents = {'red': [ "#B53331" , "" , "" , "" ]}

for s:mode in ['normal', 'insert', 'visual', 'replace']
  let g:airline#themes#ganymede#palette[s:mode].airline_error = s:AirlineError
  let g:airline#themes#ganymede#palette[s:mode].airline_warning = s:AirlineWarning
endfor

let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
let g:airline#themes#ganymede#palette.tabline = {
  \ 'airline_tab': s:N2,
  \ 'airline_tabsel': s:N1,
  \ 'airline_tabtype': [ "#F4FBFE" , "#6F641B" , "" , "" ],
  \ 'airline_tabfill': s:tabfill,
  \ 'airline_tabhid': s:IN1
  \ }
else
let s:modified = {
  \ 'airline_c': [ "#F25A55" , "" , "" , "" , "" ]
  \ }

let s:N1 = [ "#093750" , "#00B7ED" , "" , "" ]
let s:N2 = [ "#DCEBF5" , "#055682" , "" , "" ]
let s:N3 = [ "#A2D9F5" , "#0B4867" , "" , "" ]
let g:airline#themes#ganymede#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
let g:airline#themes#ganymede#palette.normal_modified = s:modified

let s:I1 = [ "#093750" , "#F1D677" , "" , "" ]
let g:airline#themes#ganymede#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
let g:airline#themes#ganymede#palette.insert_modified = s:modified

let s:V1 = [ "#093750" , "#F5837F" , "" , "" ]
let g:airline#themes#ganymede#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
let g:airline#themes#ganymede#palette.visual_modified = s:modified

let s:R1 = [ "#093750" , "#F25A55" , "" , "" ]
let g:airline#themes#ganymede#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
let g:airline#themes#ganymede#palette.replace_modified = s:modified

let s:IN1 = [ "#1C7DB1" , "#055682" , "" , "" ]
let g:airline#themes#ganymede#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
let g:airline#themes#ganymede#palette.inactive_modified = s:modified

let s:AirlineError = [ "#093750" , "#F25A55" , "" , "" ]
let s:AirlineWarning = [ "#093750" , "#F25A55" , "" , "" ]
let g:airline#themes#ganymede#palette.accents = {'red': [ "#F25A55" , "" , "" , "" ]}

for s:mode in ['normal', 'insert', 'visual', 'replace']
  let g:airline#themes#ganymede#palette[s:mode].airline_error = s:AirlineError
  let g:airline#themes#ganymede#palette[s:mode].airline_warning = s:AirlineWarning
endfor

let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
let g:airline#themes#ganymede#palette.tabline = {
  \ 'airline_tab': s:N2,
  \ 'airline_tabsel': s:N1,
  \ 'airline_tabtype': [ "#093750" , "#F1D677" , "" , "" ],
  \ 'airline_tabfill': s:tabfill,
  \ 'airline_tabhid': s:IN1
  \ }
endif
