" WARNING: Do not edit this file directly. It is generated by scripts/build.js.

let g:airline#themes#jupiter#palette = {}
let s:variant = get(g:, "jupiter_variant", "metis")

if s:variant ==# "" || s:variant ==# "jupiter"
  let s:variant = "metis"
endif

if s:variant ==# "metis"
  if &background ==# "light"
  let s:modified = {
    \ 'airline_c': [ "#B73D38" , "" , "" , "" , "" ]
    \ }
  
  let s:N1 = [ "#F7FCFE" , "#007FA3" , "" , "" ]
  let s:N2 = [ "#0B2F44" , "#D5EDF7" , "" , "" ]
  let s:N3 = [ "#335F74" , "#ECF7FC" , "" , "" ]
  let g:airline#themes#jupiter#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.normal_modified = s:modified
  
  let s:I1 = [ "#F7FCFE" , "#74772E" , "" , "" ]
  let g:airline#themes#jupiter#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.insert_modified = s:modified
  
  let s:V1 = [ "#F7FCFE" , "#A84D5E" , "" , "" ]
  let g:airline#themes#jupiter#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.visual_modified = s:modified
  
  let s:R1 = [ "#F7FCFE" , "#B73D38" , "" , "" ]
  let g:airline#themes#jupiter#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.replace_modified = s:modified
  
  let s:IN1 = [ "#5C8396" , "#D5EDF7" , "" , "" ]
  let g:airline#themes#jupiter#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
  let g:airline#themes#jupiter#palette.inactive_modified = s:modified
  
  let s:AirlineError = [ "#F7FCFE" , "#B73D38" , "" , "" ]
  let s:AirlineWarning = [ "#F7FCFE" , "#946E00" , "" , "" ]
  let g:airline#themes#jupiter#palette.accents = {'red': [ "#B73D38" , "" , "" , "" ]}
  
  for s:mode in ['normal', 'insert', 'visual', 'replace']
    let g:airline#themes#jupiter#palette[s:mode].airline_error = s:AirlineError
    let g:airline#themes#jupiter#palette[s:mode].airline_warning = s:AirlineWarning
  endfor
  
  let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
  let g:airline#themes#jupiter#palette.tabline = {
    \ 'airline_tab': s:N2,
    \ 'airline_tabsel': s:N1,
    \ 'airline_tabtype': [ "#F7FCFE" , "#74772E" , "" , "" ],
    \ 'airline_tabfill': s:tabfill,
    \ 'airline_tabhid': s:IN1
    \ }
  else
  let s:modified = {
    \ 'airline_c': [ "#F25F57" , "" , "" , "" , "" ]
    \ }
  
  let s:N1 = [ "#082D42" , "#38C2E6" , "" , "" ]
  let s:N2 = [ "#DCEBF5" , "#104B68" , "" , "" ]
  let s:N3 = [ "#9CCFE7" , "#0B3A54" , "" , "" ]
  let g:airline#themes#jupiter#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.normal_modified = s:modified
  
  let s:I1 = [ "#082D42" , "#C7C46B" , "" , "" ]
  let g:airline#themes#jupiter#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.insert_modified = s:modified
  
  let s:V1 = [ "#082D42" , "#DD747D" , "" , "" ]
  let g:airline#themes#jupiter#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.visual_modified = s:modified
  
  let s:R1 = [ "#082D42" , "#F25F57" , "" , "" ]
  let g:airline#themes#jupiter#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.replace_modified = s:modified
  
  let s:IN1 = [ "#6096B2" , "#104B68" , "" , "" ]
  let g:airline#themes#jupiter#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
  let g:airline#themes#jupiter#palette.inactive_modified = s:modified
  
  let s:AirlineError = [ "#082D42" , "#F25F57" , "" , "" ]
  let s:AirlineWarning = [ "#082D42" , "#F0A818" , "" , "" ]
  let g:airline#themes#jupiter#palette.accents = {'red': [ "#F25F57" , "" , "" , "" ]}
  
  for s:mode in ['normal', 'insert', 'visual', 'replace']
    let g:airline#themes#jupiter#palette[s:mode].airline_error = s:AirlineError
    let g:airline#themes#jupiter#palette[s:mode].airline_warning = s:AirlineWarning
  endfor
  
  let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
  let g:airline#themes#jupiter#palette.tabline = {
    \ 'airline_tab': s:N2,
    \ 'airline_tabsel': s:N1,
    \ 'airline_tabtype': [ "#082D42" , "#C7C46B" , "" , "" ],
    \ 'airline_tabfill': s:tabfill,
    \ 'airline_tabhid': s:IN1
    \ }
  endif
elseif s:variant ==# "ganymede"
  if &background ==# "light"
  let s:modified = {
    \ 'airline_c': [ "#B53331" , "" , "" , "" , "" ]
    \ }
  
  let s:N1 = [ "#F4FBFE" , "#007EA3" , "" , "" ]
  let s:N2 = [ "#093750" , "#CFEAF6" , "" , "" ]
  let s:N3 = [ "#315B71" , "#E7F5FB" , "" , "" ]
  let g:airline#themes#jupiter#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.normal_modified = s:modified
  
  let s:I1 = [ "#F4FBFE" , "#6F641B" , "" , "" ]
  let g:airline#themes#jupiter#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.insert_modified = s:modified
  
  let s:V1 = [ "#F4FBFE" , "#B6524F" , "" , "" ]
  let g:airline#themes#jupiter#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.visual_modified = s:modified
  
  let s:R1 = [ "#F4FBFE" , "#B53331" , "" , "" ]
  let g:airline#themes#jupiter#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.replace_modified = s:modified
  
  let s:IN1 = [ "#557E92" , "#CFEAF6" , "" , "" ]
  let g:airline#themes#jupiter#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
  let g:airline#themes#jupiter#palette.inactive_modified = s:modified
  
  let s:AirlineError = [ "#F4FBFE" , "#B53331" , "" , "" ]
  let s:AirlineWarning = [ "#F4FBFE" , "#B53331" , "" , "" ]
  let g:airline#themes#jupiter#palette.accents = {'red': [ "#B53331" , "" , "" , "" ]}
  
  for s:mode in ['normal', 'insert', 'visual', 'replace']
    let g:airline#themes#jupiter#palette[s:mode].airline_error = s:AirlineError
    let g:airline#themes#jupiter#palette[s:mode].airline_warning = s:AirlineWarning
  endfor
  
  let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
  let g:airline#themes#jupiter#palette.tabline = {
    \ 'airline_tab': s:N2,
    \ 'airline_tabsel': s:N1,
    \ 'airline_tabtype': [ "#F4FBFE" , "#6F641B" , "" , "" ],
    \ 'airline_tabfill': s:tabfill,
    \ 'airline_tabhid': s:IN1
    \ }
  else
  let s:modified = {
    \ 'airline_c': [ "#F25A55" , "" , "" , "" , "" ]
    \ }
  
  let s:N1 = [ "#093750" , "#00B7ED" , "" , "" ]
  let s:N2 = [ "#DCEBF5" , "#055682" , "" , "" ]
  let s:N3 = [ "#A2D9F5" , "#0B4867" , "" , "" ]
  let g:airline#themes#jupiter#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.normal_modified = s:modified
  
  let s:I1 = [ "#093750" , "#F1D677" , "" , "" ]
  let g:airline#themes#jupiter#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.insert_modified = s:modified
  
  let s:V1 = [ "#093750" , "#F5837F" , "" , "" ]
  let g:airline#themes#jupiter#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.visual_modified = s:modified
  
  let s:R1 = [ "#093750" , "#F25A55" , "" , "" ]
  let g:airline#themes#jupiter#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.replace_modified = s:modified
  
  let s:IN1 = [ "#1C7DB1" , "#055682" , "" , "" ]
  let g:airline#themes#jupiter#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
  let g:airline#themes#jupiter#palette.inactive_modified = s:modified
  
  let s:AirlineError = [ "#093750" , "#F25A55" , "" , "" ]
  let s:AirlineWarning = [ "#093750" , "#F25A55" , "" , "" ]
  let g:airline#themes#jupiter#palette.accents = {'red': [ "#F25A55" , "" , "" , "" ]}
  
  for s:mode in ['normal', 'insert', 'visual', 'replace']
    let g:airline#themes#jupiter#palette[s:mode].airline_error = s:AirlineError
    let g:airline#themes#jupiter#palette[s:mode].airline_warning = s:AirlineWarning
  endfor
  
  let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
  let g:airline#themes#jupiter#palette.tabline = {
    \ 'airline_tab': s:N2,
    \ 'airline_tabsel': s:N1,
    \ 'airline_tabtype': [ "#093750" , "#F1D677" , "" , "" ],
    \ 'airline_tabfill': s:tabfill,
    \ 'airline_tabhid': s:IN1
    \ }
  endif
elseif s:variant ==# "callisto"
  if &background ==# "light"
  let s:modified = {
    \ 'airline_c': [ "#B9353F" , "" , "" , "" , "" ]
    \ }
  
  let s:N1 = [ "#F2F6FB" , "#007EA0" , "" , "" ]
  let s:N2 = [ "#111B2A" , "#D7E1ED" , "" , "" ]
  let s:N3 = [ "#40516A" , "#E8EEF7" , "" , "" ]
  let g:airline#themes#jupiter#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.normal_modified = s:modified
  
  let s:I1 = [ "#F2F6FB" , "#4F7D25" , "" , "" ]
  let g:airline#themes#jupiter#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.insert_modified = s:modified
  
  let s:V1 = [ "#F2F6FB" , "#A93494" , "" , "" ]
  let g:airline#themes#jupiter#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.visual_modified = s:modified
  
  let s:R1 = [ "#F2F6FB" , "#B9353F" , "" , "" ]
  let g:airline#themes#jupiter#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.replace_modified = s:modified
  
  let s:IN1 = [ "#66748A" , "#D7E1ED" , "" , "" ]
  let g:airline#themes#jupiter#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
  let g:airline#themes#jupiter#palette.inactive_modified = s:modified
  
  let s:AirlineError = [ "#F2F6FB" , "#B9353F" , "" , "" ]
  let s:AirlineWarning = [ "#F2F6FB" , "#8F6100" , "" , "" ]
  let g:airline#themes#jupiter#palette.accents = {'red': [ "#B9353F" , "" , "" , "" ]}
  
  for s:mode in ['normal', 'insert', 'visual', 'replace']
    let g:airline#themes#jupiter#palette[s:mode].airline_error = s:AirlineError
    let g:airline#themes#jupiter#palette[s:mode].airline_warning = s:AirlineWarning
  endfor
  
  let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
  let g:airline#themes#jupiter#palette.tabline = {
    \ 'airline_tab': s:N2,
    \ 'airline_tabsel': s:N1,
    \ 'airline_tabtype': [ "#F2F6FB" , "#4F7D25" , "" , "" ],
    \ 'airline_tabfill': s:tabfill,
    \ 'airline_tabhid': s:IN1
    \ }
  else
  let s:modified = {
    \ 'airline_c': [ "#FF5662" , "" , "" , "" , "" ]
    \ }
  
  let s:N1 = [ "#070B12" , "#1BD7FF" , "" , "" ]
  let s:N2 = [ "#E8EEF8" , "#151E2D" , "" , "" ]
  let s:N3 = [ "#B0BED3" , "#0D1320" , "" , "" ]
  let g:airline#themes#jupiter#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.normal_modified = s:modified
  
  let s:I1 = [ "#070B12" , "#8CDD57" , "" , "" ]
  let g:airline#themes#jupiter#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.insert_modified = s:modified
  
  let s:V1 = [ "#070B12" , "#F05ADB" , "" , "" ]
  let g:airline#themes#jupiter#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.visual_modified = s:modified
  
  let s:R1 = [ "#070B12" , "#FF5662" , "" , "" ]
  let g:airline#themes#jupiter#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.replace_modified = s:modified
  
  let s:IN1 = [ "#667890" , "#151E2D" , "" , "" ]
  let g:airline#themes#jupiter#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
  let g:airline#themes#jupiter#palette.inactive_modified = s:modified
  
  let s:AirlineError = [ "#070B12" , "#FF5662" , "" , "" ]
  let s:AirlineWarning = [ "#070B12" , "#FFAD13" , "" , "" ]
  let g:airline#themes#jupiter#palette.accents = {'red': [ "#FF5662" , "" , "" , "" ]}
  
  for s:mode in ['normal', 'insert', 'visual', 'replace']
    let g:airline#themes#jupiter#palette[s:mode].airline_error = s:AirlineError
    let g:airline#themes#jupiter#palette[s:mode].airline_warning = s:AirlineWarning
  endfor
  
  let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
  let g:airline#themes#jupiter#palette.tabline = {
    \ 'airline_tab': s:N2,
    \ 'airline_tabsel': s:N1,
    \ 'airline_tabtype': [ "#070B12" , "#8CDD57" , "" , "" ],
    \ 'airline_tabfill': s:tabfill,
    \ 'airline_tabhid': s:IN1
    \ }
  endif
elseif s:variant ==# "europa"
  if &background ==# "light"
  let s:modified = {
    \ 'airline_c': [ "#9E483E" , "" , "" , "" , "" ]
    \ }
  
  let s:N1 = [ "#F8FBFC" , "#4B8FA0" , "" , "" ]
  let s:N2 = [ "#172B35" , "#DCE9ED" , "" , "" ]
  let s:N3 = [ "#4D6571" , "#EEF5F7" , "" , "" ]
  let g:airline#themes#jupiter#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.normal_modified = s:modified
  
  let s:I1 = [ "#F8FBFC" , "#617A43" , "" , "" ]
  let g:airline#themes#jupiter#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.insert_modified = s:modified
  
  let s:V1 = [ "#F8FBFC" , "#985F86" , "" , "" ]
  let g:airline#themes#jupiter#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.visual_modified = s:modified
  
  let s:R1 = [ "#F8FBFC" , "#9E483E" , "" , "" ]
  let g:airline#themes#jupiter#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.replace_modified = s:modified
  
  let s:IN1 = [ "#78909A" , "#DCE9ED" , "" , "" ]
  let g:airline#themes#jupiter#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
  let g:airline#themes#jupiter#palette.inactive_modified = s:modified
  
  let s:AirlineError = [ "#F8FBFC" , "#9E483E" , "" , "" ]
  let s:AirlineWarning = [ "#F8FBFC" , "#80652F" , "" , "" ]
  let g:airline#themes#jupiter#palette.accents = {'red': [ "#9E483E" , "" , "" , "" ]}
  
  for s:mode in ['normal', 'insert', 'visual', 'replace']
    let g:airline#themes#jupiter#palette[s:mode].airline_error = s:AirlineError
    let g:airline#themes#jupiter#palette[s:mode].airline_warning = s:AirlineWarning
  endfor
  
  let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
  let g:airline#themes#jupiter#palette.tabline = {
    \ 'airline_tab': s:N2,
    \ 'airline_tabsel': s:N1,
    \ 'airline_tabtype': [ "#F8FBFC" , "#617A43" , "" , "" ],
    \ 'airline_tabfill': s:tabfill,
    \ 'airline_tabhid': s:IN1
    \ }
  else
  let s:modified = {
    \ 'airline_c': [ "#E57965" , "" , "" , "" , "" ]
    \ }
  
  let s:N1 = [ "#0D1A24" , "#A6E8F4" , "" , "" ]
  let s:N2 = [ "#E7EEF2" , "#203342" , "" , "" ]
  let s:N3 = [ "#BAC9D0" , "#142532" , "" , "" ]
  let g:airline#themes#jupiter#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.normal_modified = s:modified
  
  let s:I1 = [ "#0D1A24" , "#B7D694" , "" , "" ]
  let g:airline#themes#jupiter#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.insert_modified = s:modified
  
  let s:V1 = [ "#0D1A24" , "#E79BD0" , "" , "" ]
  let g:airline#themes#jupiter#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.visual_modified = s:modified
  
  let s:R1 = [ "#0D1A24" , "#E57965" , "" , "" ]
  let g:airline#themes#jupiter#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
  let g:airline#themes#jupiter#palette.replace_modified = s:modified
  
  let s:IN1 = [ "#7F98A4" , "#203342" , "" , "" ]
  let g:airline#themes#jupiter#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
  let g:airline#themes#jupiter#palette.inactive_modified = s:modified
  
  let s:AirlineError = [ "#0D1A24" , "#E57965" , "" , "" ]
  let s:AirlineWarning = [ "#0D1A24" , "#D9B35F" , "" , "" ]
  let g:airline#themes#jupiter#palette.accents = {'red': [ "#E57965" , "" , "" , "" ]}
  
  for s:mode in ['normal', 'insert', 'visual', 'replace']
    let g:airline#themes#jupiter#palette[s:mode].airline_error = s:AirlineError
    let g:airline#themes#jupiter#palette[s:mode].airline_warning = s:AirlineWarning
  endfor
  
  let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
  let g:airline#themes#jupiter#palette.tabline = {
    \ 'airline_tab': s:N2,
    \ 'airline_tabsel': s:N1,
    \ 'airline_tabtype': [ "#0D1A24" , "#B7D694" , "" , "" ],
    \ 'airline_tabfill': s:tabfill,
    \ 'airline_tabhid': s:IN1
    \ }
  endif
else
  echoerr "Jupiter airline variant must be one of: metis, ganymede, callisto, europa"
endif
