" WARNING: Do not edit this file directly. It is generated by scripts/build.js.

let g:airline#themes#metis#palette = {}

if &background ==# "light"
let s:modified = {
  \ 'airline_c': [ "#B93532" , "" , "" , "" , "" ]
  \ }

let s:N1 = [ "#F8FBFD" , "#007FA8" , "" , "" ]
let s:N2 = [ "#172530" , "#DDE8EF" , "" , "" ]
let s:N3 = [ "#4A5E6B" , "#EEF5F8" , "" , "" ]
let g:airline#themes#metis#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
let g:airline#themes#metis#palette.normal_modified = s:modified

let s:I1 = [ "#F8FBFD" , "#3F7F38" , "" , "" ]
let g:airline#themes#metis#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
let g:airline#themes#metis#palette.insert_modified = s:modified

let s:V1 = [ "#F8FBFD" , "#AD3E86" , "" , "" ]
let g:airline#themes#metis#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
let g:airline#themes#metis#palette.visual_modified = s:modified

let s:R1 = [ "#F8FBFD" , "#B93532" , "" , "" ]
let g:airline#themes#metis#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
let g:airline#themes#metis#palette.replace_modified = s:modified

let s:IN1 = [ "#708390" , "#DDE8EF" , "" , "" ]
let g:airline#themes#metis#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
let g:airline#themes#metis#palette.inactive_modified = s:modified

let s:AirlineError = [ "#F8FBFD" , "#B93532" , "" , "" ]
let s:AirlineWarning = [ "#F8FBFD" , "#9D7100" , "" , "" ]
let g:airline#themes#metis#palette.accents = {'red': [ "#B93532" , "" , "" , "" ]}

for s:mode in ['normal', 'insert', 'visual', 'replace']
  let g:airline#themes#metis#palette[s:mode].airline_error = s:AirlineError
  let g:airline#themes#metis#palette[s:mode].airline_warning = s:AirlineWarning
endfor

let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
let g:airline#themes#metis#palette.tabline = {
  \ 'airline_tab': s:N2,
  \ 'airline_tabsel': s:N1,
  \ 'airline_tabtype': [ "#F8FBFD" , "#3F7F38" , "" , "" ],
  \ 'airline_tabfill': s:tabfill,
  \ 'airline_tabhid': s:IN1
  \ }
else
let s:modified = {
  \ 'airline_c': [ "#FF6B62" , "" , "" , "" , "" ]
  \ }

let s:N1 = [ "#0B1117" , "#43C7E8" , "" , "" ]
let s:N2 = [ "#DCE7EF" , "#182531" , "" , "" ]
let s:N3 = [ "#AAB8C3" , "#111A23" , "" , "" ]
let g:airline#themes#metis#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
let g:airline#themes#metis#palette.normal_modified = s:modified

let s:I1 = [ "#0B1117" , "#82C66F" , "" , "" ]
let g:airline#themes#metis#palette.insert = airline#themes#generate_color_map(s:I1, s:N2, s:N3)
let g:airline#themes#metis#palette.insert_modified = s:modified

let s:V1 = [ "#0B1117" , "#EF78C4" , "" , "" ]
let g:airline#themes#metis#palette.visual = airline#themes#generate_color_map(s:V1, s:N2, s:N3)
let g:airline#themes#metis#palette.visual_modified = s:modified

let s:R1 = [ "#0B1117" , "#FF6B62" , "" , "" ]
let g:airline#themes#metis#palette.replace = airline#themes#generate_color_map(s:R1, s:N2, s:N3)
let g:airline#themes#metis#palette.replace_modified = s:modified

let s:IN1 = [ "#738492" , "#182531" , "" , "" ]
let g:airline#themes#metis#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN1, s:IN1)
let g:airline#themes#metis#palette.inactive_modified = s:modified

let s:AirlineError = [ "#0B1117" , "#FF6B62" , "" , "" ]
let s:AirlineWarning = [ "#0B1117" , "#F2B339" , "" , "" ]
let g:airline#themes#metis#palette.accents = {'red': [ "#FF6B62" , "" , "" , "" ]}

for s:mode in ['normal', 'insert', 'visual', 'replace']
  let g:airline#themes#metis#palette[s:mode].airline_error = s:AirlineError
  let g:airline#themes#metis#palette[s:mode].airline_warning = s:AirlineWarning
endfor

let s:tabfill = airline#themes#get_highlight2(['Normal', 'bg'], ['Normal', 'bg'])
let g:airline#themes#metis#palette.tabline = {
  \ 'airline_tab': s:N2,
  \ 'airline_tabsel': s:N1,
  \ 'airline_tabtype': [ "#0B1117" , "#82C66F" , "" , "" ],
  \ 'airline_tabfill': s:tabfill,
  \ 'airline_tabhid': s:IN1
  \ }
endif
